{
 "title": "ssv-validators",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "node_job", "query": "eth-beacon" },
   { "name": "validator_job", "query": "eth-validator" },
   {
    "name": "fiat",
    "label": "Currency converter",
    "query": {
     "query": "label_values(crypto_currency,pair)"
    }
   },
   { "name": "Filters" },
   { "name": "instance", "query": "8.219.125.151" }
  ]
 },
 "panels": [
  { "title": "Validator Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Daily earning",
   "type": "stat",
   "description": "This panel shows the earning during the last day, and the annualized % of the daily earning.\n\nThose data won't be shown until the first validator is at least one day old, or that you started prometheus at least one day ago.\n\nAlso, the annualized % might be wrong if you have downtime while new validators are getting validated",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "performance1d{job=\"eth2-beacon-testnet_agent\"}",
     "legendFormat": "ETH"
    },
    {
     "expr": "performance1d{job=\"eth2-beacon-testnet_agent\"} / 32 * 365  * 100",
     "legendFormat": "Annualized %"
    }
   ]
  },
  {
   "title": "Weekly earning",
   "type": "stat",
   "description": "This panel shows the earning during the last day, and the annualized % of the daily earning.\n\nThose data won't be shown until the first validator is at least one day old, or that you started prometheus at least one day ago.\n\nAlso, the annualized % might be wrong if you have downtime while new validators are getting validated",
   "gridPos": { "h": 3, "w": 5, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "performance7d{job=\"eth2-beacon-testnet_agent\"}",
     "legendFormat": "ETH"
    },
    {
     "expr": "performance7d{job=\"eth2-beacon-testnet_agent\"} / 7 / 32 * 365  * 100",
     "legendFormat": "Annualized %"
    }
   ]
  },
  {
   "title": "Monthly earning",
   "type": "stat",
   "description": "This panel shows the earning during the last day, and the annualized % of the daily earning.\n\nThose data won't be shown until the first validator is at least one day old, or that you started prometheus at least one day ago.\n\nAlso, the annualized % might be wrong if you have downtime while new validators are getting validated",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "performance31d{job=\"eth2-beacon-testnet_agent\"}",
     "legendFormat": "ETH"
    },
    {
     "expr": "performance31d{job=\"eth2-beacon-testnet_agent\"}  / 31 / 32  * 365 * 100",
     "legendFormat": "Annualized %"
    }
   ]
  },
  {
   "title": "Yearly earning",
   "type": "stat",
   "description": "This panel shows the earning during the last day, and the annualized % of the daily earning.\n\nThose data won't be shown until the first validator is at least one day old, or that you started prometheus at least one day ago.\n\nAlso, the annualized % might be wrong if you have downtime while new validators are getting validated",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "performance365d{job=\"eth2-beacon-testnet_agent\"}",
     "legendFormat": "ETH"
    },
    {
     "expr": "performance365d{job=\"eth2-beacon-testnet_agent\"}  / 32  * 100",
     "legendFormat": "Annualized %"
    }
   ]
  },
  {
   "title": "Total earning",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "performancetotal{job=\"eth2-beacon-testnet_agent\"}",
     "legendFormat": "ETH"
    },
    {
     "expr": "performancetotal{job=\"eth2-beacon-testnet_agent\"} / 32  * 100",
     "legendFormat": "ROI"
    }
   ]
  },
  {
   "title": "Total balance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short", "label": "ETH" }
   ],
   "targets": [
    {
     "expr": "balance_sum{job=\"eth2-beacon-testnet_agent\"}",
     "legendFormat": "Total balance"
    }
   ]
  },
  {
   "title": "Validator balance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short", "label": "ETH" }
   ],
   "targets": [
    {
     "expr": "label_replace(validator_info, \"pubkey\", \"$1\", \"pubkey\", \"(.{10}).*\")",
     "legendFormat": "{{pubkey}}"
    }
   ]
  },
  {
   "title": "Validator main info",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "validator_info" }
   ]
  },
  {
   "title": "Validator Status",
   "type": "timeseries",
   "description": "Total amount of validators and total active validators\n",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "count(ssv:validator:v2:status{instance=~\"$instance.*\"} == 3)",
     "legendFormat": "Active"
    },
    {
     "expr": "count(ssv:validator:v2:status{instance=~\"$instance.*\"} != 9)",
     "legendFormat": "Total"
    },
    {
     "expr": "count(ssv:validator:v2:status{instance=~\"$instance.*\"} == 6)",
     "legendFormat": "Slashed"
    },
    {
     "expr": "count(ssv:validator:v2:status{instance=~\"$instance.*\"} == 9)",
     "legendFormat": "Removed"
    }
   ]
  },
  { "title": "Operator Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Current Health Status",
   "type": "gauge",
   "description": "Current status of the beacon, ETH1 and SSV operator node",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ssv_beacon_status{instance=~\"$instance.*\"}",
     "legendFormat": "Beacon"
    },
    {
     "expr": "ssv_eth1_status{instance=~\"$instance.*\"}",
     "legendFormat": "ETH1"
    },
    {
     "expr": "(ssv_node_status{instance=~\"$instance.*\"} + 1) or (absent(ssv_node_status{instance=~\"$instance.*\"}) * 0)",
     "legendFormat": "SSV Operator"
    },
    { "expr": "ssv_operators_web_status", "legendFormat": "SSV operators website status" }
   ]
  },
  {
   "title": "Beacon Node Health",
   "type": "timeseries",
   "description": "Health status of the beacon node",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 19 },
   "targets": [
    { "expr": "ssv_beacon_status" }
   ]
  },
  {
   "title": "ETH1 Node Health",
   "type": "timeseries",
   "description": "Health status of the ETH1 node",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 19 },
   "targets": [
    { "expr": "ssv_eth1_status" }
   ]
  },
  {
   "title": "SSV Operator Node Health",
   "type": "timeseries",
   "description": "Health status of the SSV operator node",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "ssv_node_status + 1", "legendFormat": "{{pod}}" },
    { "expr": "absent(ssv_node_status) * 0" }
   ]
  },
  {
   "title": "SSV operators website status",
   "type": "timeseries",
   "description": "Health status of the SSV operator node",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ssv_operators_web_status",
     "legendFormat": "https://ssv-operators-test.nodeplus.io/"
    }
   ]
  },
  {
   "title": "current_block_height",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "current_block_height{job=\"eth2-beacon-testnet_agent\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "beacon_block_height",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "beacon_head_slot{job=\"eth2-beacon-testnet_agent\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "block_height_behind",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "current_block_height-beacon_head_slot{job=\"eth2-beacon-testnet_agent\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "block_height_behind",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 14, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "current_block_height-beacon_head_slot{job=\"eth2-beacon-testnet_agent\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Node process started",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 17, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time()-process_start_time_seconds{job=\"eth-beacon-testnet\"})/3600",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "beacon_version_info",
   "type": "table",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 24 },
   "targets": [
    {
     "expr": "version_info{job=\"eth2-beacon-testnet_agent\"}*on(instance) group_left(nodename) (node_uname_info)"
    }
   ]
  },
  {
   "title": "Ssv Operator Estimated Remaining Days",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "estimated_remaining_days",
     "legendFormat": "ssv_operator_estimated_remaining_days"
    }
   ]
  },
  {
   "title": "Balance Remaining",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 9, "y": 29 },
   "targets": [
    { "expr": "balance", "legendFormat": "balance" },
    { "expr": "balance_threshold_warning", "legendFormat": "balance_threshold_warning" },
    { "expr": "balance_threshoid", "legendFormat": "balance_threshoid" }
   ]
  },
  {
   "title": "ALERTS",
   "type": "stat",
   "gridPos": { "h": 1, "w": 5, "x": 19, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  { "title": "All alerts", "type": "alertlist", "gridPos": { "h": 24, "w": 5, "x": 19, "y": 30 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg(rate(node_cpu_seconds_total{mode=\"idle\",job=\"testnet-agent\"}[1m])) by (instance) * 100)*on(instance) group_left(nodename) (node_uname_info) ",
     "legendFormat": "ssv-{{nodename}}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 9, "y": 37 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100.0 - 100 * ((node_filesystem_avail_bytes{job=\"testnet-agent\"} / 1024 / 1024 ) / (node_filesystem_size_bytes  / 1024 / 1024))* on(instance) group_left(nodename) (node_uname_info)",
     "legendFormat": "ssv-{{nodename}}- {{mountpoint}}"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100*(node_memory_MemTotal_bytes - node_memory_MemFree_bytes - node_memory_Buffers_bytes - node_memory_Cached_bytes{job=\"testnet-agent\"}) / node_memory_MemTotal_bytes *on(instance) group_left(nodename) (node_uname_info)",
     "legendFormat": "ssv-{{nodename}}"
    }
   ]
  },
  {
   "title": "DISK IO",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 9, "y": 44 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{job=\"testnet-agent\"}[1m]) *on(instance) group_left(nodename) (node_uname_info)",
     "legendFormat": "ssv-{{nodename}}-{{device}}_read"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{job=\"testnet-agent\"}[1m]) *on(instance) group_left(nodename) (node_uname_info)",
     "legendFormat": "ssv-{{nodename}}-{{device}}_write"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 51 },
   "repeat": "node",
   "yaxes": [
    { "format": "bits", "label": "bits in (-) / bits out (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"testnet-agent\"}[1m])*8*on(instance) group_left(nodename) (node_uname_info)",
     "legendFormat": "ssv-{{nodename}}-{{device}}_in"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"testnet-agent\"}[1m])*8*on(instance) group_left(nodename) (node_uname_info)",
     "legendFormat": "ssv-{{nodename}}-{{device}}_out"
    }
   ]
  },
  {
   "title": "ETH Warn: The process just restarted",
   "type": "graph",
   "description": "This alert is useful only for people who has automatic restart of the process after crash. \nThis can be made for example by using the prysm.bat file on windows with \"set PRYSM_AUTORESTART=true&\", or with docker with \"--restart always\"",
   "gridPos": { "h": 1, "w": 5, "x": 19, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(time()-process_start_time_seconds{job=\"eth-beacon-testnet\"})/3600",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "ETH Alert: 50 slots behind",
   "type": "graph",
   "gridPos": { "h": 1, "w": 5, "x": 19, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "beacon_clock_time_slot-beacon_head_slot{job=\"eth-beacon-testnet\"}",
     "legendFormat": "node slots behind"
    }
   ]
  },
  {
   "title": "ETH Alert: Process down",
   "type": "graph",
   "gridPos": { "h": 1, "w": 5, "x": 19, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "up{job=\"eth-beacon-testnet\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "ETH Alert: Participation rate < 66%",
   "type": "graph",
   "gridPos": { "h": 1, "w": 5, "x": 19, "y": 57 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "beacon_prev_epoch_target_gwei/beacon_prev_epoch_active_gwei{job=\"eth-beacon-testnet\"}*100",
     "legendFormat": "{{alias}}"
    }
   ]
  }
 ]
}